# Generated by Django 4.0.3 on 2022-03-21 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardTypeName', models.CharField(max_length=255)),
                ('cardTypeDescription', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'cardTypes',
                'db_table': 'cardType',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=255)),
                ('cardDescription', models.TextField(blank=True, max_length=255, null=True)),
                ('cardTypeId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.cardtype')),
            ],
            options={
                'verbose_name_plural': 'cards',
                'db_table': 'card',
            },
        ),
    ]
